# Generated by Django 3.2.8 on 2021-12-03 10:35

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(help_text='Enter a Country name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular customer across whole shop', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=20)),
                ('shipping_address', models.CharField(help_text='Shipping Address', max_length=200)),
                ('billing_address', models.CharField(help_text='Billing Address', max_length=200)),
                ('password', models.CharField(max_length=50)),
                ('ph_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('counrty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theretailerapp.country')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'pending'), ('delivered', 'delivered'), ('cancelled', 'cancelled'), ('approved', 'approved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('order_shipping_address', models.CharField(help_text='Shipping Address', max_length=200)),
                ('order_price', models.FloatField()),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theretailerapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole shop', primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Enter first name', max_length=50)),
                ('description', models.CharField(help_text='Description of the product', max_length=1000)),
                ('price', models.FloatField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theretailerapp.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theretailerapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='BasketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('basket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theretailerapp.basket')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theretailerapp.product')),
            ],
        ),
        migrations.AddField(
            model_name='basket',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theretailerapp.customer'),
        ),
    ]
