# Generated by Django 3.2.8 on 2021-11-11 09:38

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(help_text='Enter a Country name', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole shop', primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Enter first name', max_length=50)),
                ('description', models.CharField(help_text='Description of the product', max_length=1000)),
                ('price', models.FloatField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular customer across whole shop', primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='Enter first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=20)),
                ('shipping_address', models.CharField(help_text='Shipping Address', max_length=200)),
                ('billing_address', models.CharField(help_text='Billing Address', max_length=200)),
                ('ph_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('customer_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
                ('user_password', models.CharField(max_length=50)),
                ('counrty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theretailerapp.country')),
            ],
        ),
    ]
