# Generated by Django 3.2.8 on 2021-11-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='customer_email',
            new_name='email',
        ),
    ]
