# Generated by Django 3.2.8 on 2021-11-01 06:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0002_auto_20211029_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular product across whole shop', primary_key=True, serialize=False)),
                ('product_name', models.CharField(help_text='Enter first name', max_length=50)),
                ('description', models.CharField(help_text='Description of the product', max_length=1000)),
                ('price', models.FloatField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('created_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular customer across whole shop', primary_key=True, serialize=False),
        ),
    ]
