# Generated by Django 3.2.8 on 2021-11-01 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0003_auto_20211101_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='ph_number',
            field=models.CharField(default='None', help_text='phone number', max_length=12),
        ),
    ]
