# Generated by Django 3.2.8 on 2021-11-11 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0005_alter_customer_ph_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
