# Generated by Django 3.2.8 on 2021-11-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0006_alter_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default=123456, max_length=50),
            preserve_default=False,
        ),
    ]
