# Generated by Django 3.2.8 on 2021-11-17 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0008_basket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket',
            name='id',
        ),
        migrations.AlterField(
            model_name='basket',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='theretailerapp.customer'),
        ),
    ]
