# Generated by Django 3.2.8 on 2021-11-17 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0009_auto_20211117_0910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
