# Generated by Django 3.2.8 on 2021-11-17 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0012_approvalstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placed_at', models.DateField(blank=True, null=True)),
                ('approval_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='theretailerapp.approvalstatus')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theretailerapp.customer')),
            ],
        ),
    ]
