# Generated by Django 3.2.8 on 2021-11-18 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0013_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_shipping_address',
            field=models.CharField(default=None, help_text='Shipping Address', max_length=200),
            preserve_default=False,
        ),
    ]
