# Generated by Django 3.2.8 on 2021-11-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0015_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_price',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
