# Generated by Django 3.2.8 on 2021-11-30 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theretailerapp', '0019_auto_20211130_0903'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='placed_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='order',
            name='updated_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
